title: Xi (Chase) Jiang
logo: /profile_pic.jpg
description: Ph.D. Student in Computer Science at University of Chicago
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
gems:
  - jekyll-sitemap
whitelist:
  - jekyll-sitemap
